eaburns/T

edit/addr.go
edit/addr_test.go
edit/bench_test.go
edit/edit.go
runes/bench_test.go
runes/runes.go
runes/runes_test.go

It reads better and is more consistent with bytes.Buffer.

Rename buffer.Runes to runes.Buffer.

---

edit/addr.go
edit/addr_test.go
re1/re1.go
re1/re1_test.go

Add address parsing

---

edit/edit.go
edit/edit_test.go

It performs edits parsed from sam-style edit commands.

Add Editor.Edit.

---

ui/play/main.go
ui/sdl2/sdl2.go
ui/ui.go

Drawing textures can be significantly more efficient than drawing general images.
Fixes #60.

Add improved texture-based image support.

---

font/font.go
gui/gui.go
gui/textarea.go
gui/textarea_test.go

Right now it only has TextArea and support for laying out lines of text.

Add the gui package.

---

ui/sdl2/sdl2.go

This is a cute idea inspired by some old John Asmuth post.
I haven't read the post in years, nor did I re-read it now
(so my implementation may be a bit different),
but here it is for reference:
http://gowithconfidence.tumblr.com/post/31426832143/stacked-channels

Simplify sdl2's unbounded channel.

---

edit/addr.go

The previous implementation was cute; it had more methods, each with fewer conditions. But it was hard to follow. I blame gocyclo. This change basically inlines the former clip and move methods right into addr.update.

Simplify addr.update.

---

edit/edit.go
edit/edit_test.go

Am I doing this right? It feels like I'm not.
Anyways, pull fix for #92 to the main branch.

Fix for issue 92

---

edit/edit.go
edit/edit_test.go

WhereLine will return the line address of a given address.
The "=" edit command will return the line(s) of an address.
This command differs slightly from sam which returns both the line(s)
and the character address.
Fixes #97.

Added WhereLine and "=" edit command

---

edit/edit.go
edit/edit_test.go

I decided to keep both n and g, it seemed like would have gotten a little confusing in the code if we had decided to go with "if g is present n = -n..." and the resulting code that would ensue.

substitution pull request

---

edit/editor.go

• Trim preceeding horizontal whitespace.
• Don't chomp the final newline (preceeding .) in multi-line text. Sam leaves it, so that multi-line text always ends with a newline.
• Allow literal newlines in delimited text by escaping n.
• Simplify the logic. Among other things, no need to special-case digit escaping. It happens by default.

Fix newlines and whitespace in c, a, and i edits.

---

edit/addr.go
edit/addr_bench_test.go
edit/addr_test.go
edit/editor.go

The editor uses where for evaluating addresses.
I like it better than addr.

Rename Address.addr to Address.where.

---

edit/editor.go
edit/editor_test.go
edit/runes/runes.go

They provide io.Reader/io.Writer access to an Editor.

Add Editor.ReaderFrom and Editor.WriterTo.

---

edit/runes/buffer_test.go
edit/runes/runes_test.go

Be sure to clean things up when done with them and not later, to avoid "too many open files" errors

Cleanup temp files in tests

---

README.md

Add a simple README file explaining T, what it is, and what it plans to be.

Create README.md file.

---

AUTHORS

After years of reviewing, he finally actually changed some code.

Add Steve McCoy to the AUTHORS file.

---

edit/addr.go
edit/edit.go

Strings copy on append, so appending single runes leads to quadratic behavior. Use []rune and convert to a string after.

Don't append single runes to strings in a loop, use []rune.

---

edit/edit.go

Use io.RuneScanner in edit package doc examples.

---

ted/ted.go

It is like `sam -d`, but using T's edit package.

Add the experimental Ted editor.

---

ted/ted.go

Remember the latest e or w file, and use that path on subsequent w commands if they do not have an argument.

ted: remember e or w file on subsequent w.

---

edit/buffer.go
edit/edit_test.go
edit/runes/buffer.go

Fix a couple of big bugs relating to undo/redo.

Fix undo redo

---

edit/addr.go
edit/addr_test.go
edit/buffer.go
edit/buffer_test.go
edit/text.go

edit: add !, clamped simple addresses.

---

edit/addr_bench_test.go
edit/addr_test.go
edit/buffer.go
edit/buffer_test.go
edit/edit.go
edit/edit_test.go
edit/runes/buffer.go
edit/runes/buffer_test.go
edit/text.go

I started the HTTP editor server. It needed Editor.Change to return the size of text read. While I was at it, I made a few other small changes.

edit: various small changes.

---

editor/client.go
editor/editor.go
editor/editor_test.go
editor/server.go
gok.sh
ted/ted.go

It provides a client and server for a simple HTTP editor API, serving the T edit language.

editor: add the editor package.

---

editor/editor_test.go
editor/server.go

Some day we'll have this right.

editor: fix more locking bugs

---

.travis.yml

It now contains the fix for issue 61.

travis.yml: use mattn/goveralls.

---

edit/addr.go
edit/addr_test.go
edit/edit_test.go
editor/editor_test.go

And add a new : address which is like , but allows the addresses in reverse order.

Take caution back from the wind, restore address errors.

---

editor/client.go
editor/editor.go
editor/editor_test.go
editor/server.go

It is a websocket endpoint for watching changes made to the buffer.

editor: add /buffer/<ID>/changes.

---

editor/benchmark_test.go
editor/editor_test.go
editor/editortest/editortest.go
editor/server.go
editor/view/view.go
editor/view/view_test.go
ui/client.go
ui/main.go
ui/server.go
ui/sheet.go
ui/textbox.go
ui/ui.go
ui/ui_test.go
ui/window.go
ui/window_test.go

Just simple editing for the moment. You can only add and remove from the end of the buffer. However, the infrastructure is there for more complete editing, it just needs UI work to use it.

ui: add editable text.

---

ui/main.go

ui: don't take over the main thread

---

ui/edit_test.go
ui/sheet.go
ui/textbox.go
ui/window.go

ui: move dot on mouse click.

---

ui/window.go
ui/window_test.go

Added in a bool to specify if the setBounds events are being triggered by a window resize to allow for special handling in anything implemented as a Frame (also for window and column).

Keep column tags fixed height while window resizes

---

editor/view/view_test.go

This test could have been easily done right within the established framework.

edit/view: simplify a test.

---

edit/addr_test.go

I was trying to expose a potential bug, but there is no bug.

edit: add a couple more .-0 tests.

---

editor/view/view.go
ui/textbox.go

ui: fix regexp selecting 2-click command.
