edit/addr.go
edit/addr_bench_test.go

edit.Regexp requires the regular experssions to be delimited.
The benchmark expressions didn't begin with a delimiter.
However, since we never checked the error,
we missed that it was failing for the medium and hard cases.
Now we return ErrNoMatch if the expression fails to match.
The benchmark ensures that this is the result
(since it never expects to match).
Now the benchmarks make sense:
BenchmarkRegexpEasy0x32	   10000	    124121 ns/op	   0.26 MB/s
BenchmarkRegexpEasy0x1K	   10000	    140324 ns/op	   7.30 MB/s
BenchmarkRegexpEasy1x32	   20000	     98823 ns/op	   0.32 MB/s
BenchmarkRegexpEasy1x1K	   10000	    113419 ns/op	   9.03 MB/s
BenchmarkRegexpMediumx32	   10000	    130109 ns/op	   0.01 MB/s
BenchmarkRegexpMediumx1K	   10000	    157064 ns/op	   6.52 MB/s
BenchmarkRegexpHardx32 …

Fix regexp address benchmarks.

---

edit/addr.go
edit/addr_bench_test.go
edit/addr_test.go
edit/edit.go
edit/edit_test.go
gok.sh

To remove some special cases, dot is just a mark named '.'.
But you cannot create a mark named '.', so it can never be accidentally overridden.
Also, dots and marks can never be out-of-range.
Instead of returning an error if this happens, panic.
Also also, change Dot, End, and All from functions to variables.
Upside: removes noisy parentheses in addresses.
Downside: they could be accidentally re-assigned to junk.
But the downside never happens in practice.
Consider ErrWhatever variables.
They could be reassigned too.
It just never comes up.

Implement mark addresses.

---

edit/addr.go

It use to say that it returned a regular expression address without explaining what that is.
Now it explains that it returns an address identifying the next match.

Clarify the comment on edit.Regexp.

---

edit/addr.go
edit/edit.go
re1/bench_test.go
re1/re1.go
re1/re1_test.go
runes/runes.go
runes/runes_test.go

This is more verbose all over the place, but it obviates the need to panic IO errors.
Fixes #39.

Change re1.Runes.Rune to return an error.

---

edit/addr.go
edit/addr_test.go
edit/edit.go
re1/bench_test.go
re1/re1.go
re1/re1_test.go
runes/runes.go
runes/runes_test.go

The interface is prettier without the error.
Instead of the original apporach of panicing on IO errors,
store errors in the Runes implementer and check it
before determining if a match succeeds.

Don't return an error from re1.Match.

---

ui/play/main.go
ui/sdl2/sdl2.go
ui/ui.go

There was a deadlock between sdl2UI.run and the main event loop
if the main event loop both send to sdl2UI.do (Window.Draw)
and also received from Window.Events().
The sdl2UI.run go routine would block sending on Window.Events()
and the main loop go routine would block sending on sdl2UI.do.
This is the classic dining philosophers problem.
To break the deadlock, I introduced a new go routine
that proxies events from sdl2UI.run
to the window's output event channel.
This way, the events are received in the order that they are sent
and sdl2UI.run never blocks sending an event—the proxy go routine
is always able to receive an event from sdl2UI.run.
Fixes #58.

Fix a deadlock between sdl2UI.do and window.event.

---

ui/play/main.go
ui/sdl2/sdl2.go
ui/ui.go

This removes the SetColor method.
There are only two methods that need the color;
they can just take it as an argument.
I also swapped the order of the arguments to Canvas.Draw.
Fill and Stroke take the color first and the location second.
Draw should take the image, which specifies the colors,
first and the location second too.

Make the ui.Canvas API stateless.

---

ui/play/main.go

Otherwise, we may close d1.tex in the defer
after w1 has been closed from the CloseEvent.
I don't think that's allowed,
and I think it's causing OSX to barf.
Fixes #65.

Don't bother closing textures on exit.

---

font/font.go
font/font_test.go
font/testfont/testfont.go

It provides a layer of indirection between the user and truefont.
This serves two purposes:
1. It will make it easier to replace truefont with freetype-go once the latter supports everything that we need.
2. It allows for the creation of a fake test font, for use in testing the eventual text layout code.

Add the font package.

---

edit/edit_test.go

Previously it was printing the nil error coming from regexp.MatchString, not the error coming from the Editor.Do method.

Print the correct error on error mismatch in eTests.

---

edit/edit_test.go

I panicked because I thought
s/(=*)/---\1---/
on a buffer with
...===...
would give
...---===---...
It doesn't. I forgot that /(=*)/ can match ε. It just replaces the ε at the beginning of the buffer:
------...===...
This is not a bug. It's expected. Instead, use s/(=+)/---\1---/
These added tests simply remind us of this fact.

Add a two paranoid, substitute tests.

---

edit/addr_test.go
edit/editor.go
edit/editor_test.go
edit/log_test.go
edit/runes/buffer_test.go
gok.sh

1) There were bugs in the Buffer Close code.
2) Lots of tests forgot to correctly close Buffers.
3) gok.sh now checks for leaks so they can be found more quickly.

Fix tmp files leaks.

---

edit/edit_test.go

The tests assume a bourne-compatible shell for redirect syntax etc.
This helps with #126, but it still requires /bin/sh.

Use /bin/sh for TestPipe* tests.

---

gok.sh

Use mktemp instead of tempdir in gok.sh.

---

edit/edit.go

I remembered the primary reason not to use the standard regexp package: it doesn't support reverse matching. I changed the comment to say as much. I also simplified it somewhat.

Change the edit package doc not on regexps.

---

edit/addr_test.go

otherwise, build errors on 32bit.

Use FormatInt instead of Itoa, which takes int instead of int64.

---

edit/addr.go
edit/addr_test.go
edit/edit.go
edit/edit_example_test.go
edit/edit_test.go
re1/bench_test.go
re1/re1.go
re1/re1_test.go

These functions used to take a []rune and return their result and the un-parsed, leftover runes. This made for lots of ugly slicing to track the leftover runes. It also limited the use of the functions.
Since there is no way before parsing with Ed or Addr to know when the edit or address end, it was impossible to parse an Edit or Address from an io.Reader. The best one could do was scan lines from the input and parse each line. But some crucial Edits span multiple lines (for example, the multi-line variants of c, i, and a).
Now, these functions take a io.RuneScanner. This has two improvements:
1) In my opinion, the code is more straight-forward. The io.RuneScanner tracks the left over runes, so it needn't be done explicitly.
2) Lots of things implement io.RuneScanner. To name a few:
* …

Change Ed and Addr to use io.RuneScanner.

---

edit/addr_test.go

2f57088c3e73e8325cf31b8831f946abd4e288d0 changed the way that escaped meta-character delimiters behave. Namely, they used to be interpreted as meta, but now they are interpreted as literal. There was concern that this would break Dot.Minus(Regexp("…")) addresses, where the regexp contained a meta ?. The worry was that, internally, Regexp addresses would switch the given delimiter to a ? to track the reversing. This would mean that any meta-? characters would be escaped and now be interpreted literally instead of meta. However Regexp does not work this way; whe reversing, it keeps the original delimiter. If the user used ? originally, then they had the new behavior of meta-? from the start; Regexp never changes it out from beneath them. The added tests verify.
However, we should switch …

Add tests for reversing regexps containing meta ?.

---

edit/addr_test.go
re1/re1.go
re1/re1_test.go

1. Treat escaped metacharacter delimiters as meta, not literal.
2. Number nested subexpressions in order of their (, not their ).

Fix a couple of re1 bugs.

---

re1/re1.go
re1/re1_test.go

This makes the parsing more straight-forward. It also fixes a bug with trailing `\`.
Fixes #149.
Fixes #147.

Rewrite the re1 parser to tokenize the input.

---

edit/addr.go
gok.sh

No need to specify Address in the declaration of All, it will be correctly inferred.
We still need to specify SimpleAddress for Dot and End, or else they will be inferred as the unexported type simpleAddr.

Fix a golint complaint.

---

edit/addr.go
edit/addr_bench_test.go
edit/addr_test.go
edit/edit.go
edit/edit_example_test.go
edit/edit_test.go
edit/editor_test.go
re1/delim.go
re1/delim_test.go

Don't require delimiters for regexps.
Properly escape delimiters in Substitution edits.

Delimiter fixes

---

edit/addr.go
edit/addr_test.go

Allow any non-space rune for mark edits.

---

edit/addr.go
edit/addr_test.go
edit/edit.go

Also fix a bug where , and ; were parsed as right-associative instead of left.
The string representation can only have one associativity. If we allow both left and right associative addresses, then one of them must not have a string representation.
For example,
The string representation of `Line(0).To(Line(1).To(Line(2)))` would be `0,1,2`.
The string representation of `Line(0).To(Line(1)).To(Line(2))` would be `0,1,2`.
But `0,1,2` parses right-associative so the first is wrong. It has no valid string representation.
Now, `Line(0).To(Line(1).To(Line(2)))` is not possible,
because `Line(1).To(Line(2))` returns an Address,
but `Line(0).To(·)` requires an AdditiveAddress.
In addition, we used to allow , and ; to take precedence over + and -.
One could write …

Disallow right-associative and invalid precedence addresses.

---

edit/addr_bench_test.go

Close buffer in address benchmarks.

---

edit/addr.go
edit/addr_test.go

• Instead of overriding SimpleAddress.where, Clamp used the embedde SimpleAddress's where method, completely negating any clamping.
• TestEditClamp and TestEditClampFromString were testing the dot tests.
• cleanup: I moved the one-line reverse() methods for SimpleAddresses up to the block of other one-line methods.

edit: fix completely broken clamp address.

---

edit/addr_bench_test.go
edit/addr_test.go
edit/buffer.go
edit/buffer_test.go
edit/edit.go
edit/edit_test.go
edit/text.go

This cuts down on the error boilerplate code in the Edit implementations.
I also added setDot, which sets the '.' mark and panics on error.
It is called by Edit implementations after Address.Where computes a Span.
Such Spans can't be out of range or else Address.Where would have returned the error.

edit: defer reporting Editor.Change errors until Editor.Apply.

---

editor/editor_test.go
editor/server.go

Switch to RWMutex, and release locks early instead of hanging onto them for the entire handler.

editor: finer-grained locking in the server.

---

editor/client.go
editor/editor.go
editor/editor_test.go
editor/server.go

There's no more Client type. Instead, users maintain all necessary state in a url.URL (the url, path to methods, and in the future the token). The paths now use a much flatter namespace too:
/buffers is the list of buffers
/buffer/{id} is the buffer with the given ID.
/buffer/{id}/editors is the list of a buffer's editors
/editor/{id} is the editor with the given ID.

editor: rewrite the editor API to use paths instead of IDs.

---

ui/text/main.go
ui/text/text.go
ui/text/text_test.go

1. set text based only on the box size, not it's minimum point, which is irrelevant and required lots of needless resetting when sliding text boxes around.
2. don't double-fill, just fill padding separately.
3. support non-zero-width newlines — found in some TTF fonts, apparently.
4. fix end-of-line tabs — they were causing lines to appear too wide to draw.
5. other minor tweaks.

ui/text: various improvements and fixes.

---

editor/server.go
websocket/websocket.go

There is no way to prevent these errors. They occur when the remote peer closes the connection while a send is in progress. It's not log-worthy, it just means that the watcher is finished.

editor: don't log harmless "send after close" errors.

---

ui/window.go

The x11driver fix was merged by https://go-review.googlesource.com/#/c/22118.

ui: remove DPI hack.

---

editor/view/view.go
editor/view/view_test.go
ui/column.go
ui/edit_test.go
ui/sheet.go
ui/textbox.go
ui/window.go
ui/window_test.go

We were returning errors from individual edits, but if the entire HTTP request failed, no error was returned, and the response channel was never notified. This caused any such error to deadlock waiting for a response that would never be sent. Now, the interface is changed to hide the underlying channel and simply return the response or an error instead.
This change also makes the ui code more explicit about whether it's doing a synchronous or asynchornous request. This is important, because we want to avoid blocking the window's event goroutine on synchronous requests, which we currently do in a few places (see #295).
Fixes #293.

editor/view,ui: return errors preforming edits on a View.
